package ku.user.user.mock;

import ku.user.domain.user.infrastructure.entity.UserEntity;
import ku.user.domain.user.infrastructure.repository.UserRepository;

import java.util.*;
import java.util.concurrent.atomic.AtomicLong;

public class FakeUserRepository implements UserRepository {
    private final AtomicLong autoGeneratedId = new AtomicLong(0);
    private final List<UserEntity> data = Collections.synchronizedList(new ArrayList<>());
    @Override
    public Optional<UserEntity> findById(Long id) {
        return data.stream().filter(item -> item.getId().equals(id)).findFirst();
    }

    @Override
    public Optional<UserEntity> findByEmail(String email) {
        return data.stream().filter(item -> item.getEmail().equals(email)).findFirst();
    }

    @Override
    public Optional<UserEntity> findByNickname(String nickname) {
        return Optional.empty();
    }

    @Override
    public UserEntity save(UserEntity user) {
        if (user.getId() == null || user.getId() == 0) {
            UserEntity newUser = UserEntity.builder()
                    .email(user.getEmail())
                    .nickname(user.getNickname())
                    .build();
            data.add(newUser);
            return newUser;
        } else {
            data.removeIf(item -> Objects.equals(item.getId(), user.getId()));
            data.add(user);
            return user;
        }
    }

    @Override
    public void delete(UserEntity userEntity) {

    }

    @Override
    public boolean existEmail(String email) {
        return data.stream().anyMatch(item -> item.getEmail().equals(email));
    }

    @Override
    public boolean existNickname(String nickname) {
        return data.stream().anyMatch(item -> item.getNickname().equals(nickname));
    }
}
